---
title: Post 3
author: Team Rreproduce
date: '2022-10-28'
slug: []
categories: []
tags: []
description: ~
toc: yes
authors: []
series: []
lastmod: '2022-10-28T09:31:54-04:00'
featuredVideo: ~
featuredImage: ~
---
The three fundamental principles of analyzing data of human subjects adapted from the Belmont Report are crucial for researchers to follow. Adhering to all three principles ensures the ethics of conducting human subject research, avoiding the conflict of interests, and securing the benefits of both researchers and participants.

We found beneficence to be the most important principle to adhere to in the context of our project. Two of our datasets, crime rate and adolescence to adult development, contains sensitive information, such as drug use and crime rate. Despite the sensitive information, analyzing the potential factors that are associated with crime rate and drug use, such as parental relationships and neighborhood environment, would bring significant insights into preventing the negative behaviors and related outcomes. We deem this endeavor outweighing the harm. As long as the data are non-identifiable, analysis would not harm individual’s rights to reserve sensitive personal information. Nevertheless, considering the re-identifiable risk, we are going to make sure to revisit the consent from the original research protocols and avoid cases of relatively small numbers. 

Another principle we found important is under Justice: return data and research results to community members in a form they can use. Most participants chose to release information for studies partly because they would like to make contributions for the development of science. They might want their data and the associated result to be generalizable to the public, and they might hope to derive insights from themselves for knowledge and educational opportunities. Thus, we hope to disseminate our research results to the source of the data, expressing the gratification on the resources it offered, while communicating science with the communities using unbiased, trustworthy venues for the maximized benefits of the participants.