---
title: Big Picture
description:
toc: true
featuredImage: 
featuredVideo: shiny_app/video/MA415 proj 2022-12-12 21.03.08.mp4
draft: false
---

<font size="5"><b>Big Question: Which state will be the best choice for Amy to migrate?</font></b>


Interactive: https://chenkaiyao2000.shinyapps.io/shiny/

In most cases, we cannot decide where we are born and live at a younger age, but when we grow up, we get the chance to decide where we want to live by migrating to other states, even other countries. In the first dataset about migration decisions, we specifically look at the place the participants live at 16 years old and the place they live when they are 26 years old.  Because before the age of 16 years old, people mainly stay in the states they were originally born in or where their family is.	However, during their age from 16 years old to 26 years old, they get the chance to migrate because of the university's location and working location. 


Among my friends, the location is one of the factors when they choose the graduate school and working location. The safety level（ especially crime rate)  of the state is one of the primary things in consideration. Therefore, we choose the dataset about migration trend and crime rate to explore the relationship in between.  
 
 
Therefore, let us introduce Amy and help her make the migration decision throughout our exploring process! 


Amy is a 20 years old girl studying advertising in Boston University. As a rising sophomore, it is the time to start thinking about graduate school’s application list and jobs. She has a strong desire to leave Boston, where she originally came from. Therefore, location is definitely one key factor in consideration. 
 
 
Our unifying hypothesis is : <b>The quality of life standard in each state will have an impact on people’s migration decision from 16 years old to 26 years old.</b>

[Next Page: Dig Into Data](/big_picture2/)
