---
title: Post 1
author: Team Rreproduce
date: '2022-10-14'
slug: []
categories: []
tags: []
description: ~
toc: yes
authors: []
series: []
lastmod: '2022-10-14T11:38:54-04:00'
featuredVideo: ~
featuredImage: ~
---
## Intro
This week our group found three datasets from distinct fields. 

## Data 1: Young Adult Migration 
Data source link: https://migrationpatterns.org/

This data tracks the people born in the U.S. between 1984 and 1992 where they lived at the age of 16 and where they live at the age of 24. 

Dataset has ~13 million samples and its parameters are:

  - origin commuting zone (o_cz)
  
  - o_state
  
  - destination commuting zone (d_cz)
  
  - d_state
  
  - parental income quantile
  
  - race
  
  - number of people from o now living in d
  
  - number of people living in d
  
  - number of people from o
  
Research Questions:

  - Which city is the most popular for young adult immigrants?
  
  - Which city has the most young adults who want to move out?
  
  - What parameters influence the immigration decisions? (race, parents income, other datasets maybe education level, married, city GDP, government policy, tax rate, weather)

---
## Data 2: National Longitudinal Study of Adolescent to Adult Health

Data source link: https://dataverse.unc.edu/dataverse/addhealth


---
## Data 3: International Homicide

Data source link: https://dataunodc.un.org/dp-intentional-homicide-victims 

Data are collected from national authorities through the annual United Nations Crime Trends Survey(UN- CTS). Additional data are sourced from the most reliable sources available. All data are sent to UN Member States for review and validation. Estimate based on UNODC homicide statistics. Male and Female rates are calculated based on the male or female population of the corresponding age group while total is based on the total population (both sexes) of the corresponding age group.

Dataset has ~76000 entries and its parameters includes:

  - country
  
  - subregion
  
  - indicator
  
  - sex
  
  - age
  
  - region
  
  - unit of measurement
  
  - value
  
  - source 
  
and more 

Research Questions: 

  - Which region of the world has the largest proportion of homicide cases?
  
  - How’s the trend of homicide cases look like?
  
  - What parameters influence the homicide rate? (country GDP, government policy, tax rate, education level, etc.)
